version: '3.5'

services:

  php-fpm:
    container_name: docker-compose-boilerplate-php-fpm-${APP_ENV:-dev}
    build:
      context: .
      target: ${APP_ENV:-dev}
      dockerfile: .docker/php-fpm/Dockerfile
      args:
        APP_ENV: ${APP_ENV:-dev}
        TZ: ${TZ:-Europe/Kiev}
    volumes:
      - ./:/var/www/html:rw
      - ~/.composer:/root/.composer/cache
    networks:
      - docker-compose-boilerplate

  nginx:
    container_name: docker-compose-boilerplate-nginx-${APP_ENV:-dev}
    build:
      context: .
      target: ${APP_ENV:-dev}
      dockerfile: .docker/nginx/Dockerfile
      args:
        APP_ENV: ${APP_ENV:-dev}
    volumes:
      - ./:/var/www/html:rw
      - ./var/log/nginx:/var/log/nginx:rw
    ports:
      - ${NGINX_PORT:-8080}:80
    depends_on:
      - php-fpm
    networks:
      - docker-compose-boilerplate

###> doctrine/doctrine-bundle ###
  mariadb:
    container_name: docker-compose-boilerplate-mariadb-${APP_ENV:-dev}
    build:
      context: .
      target: ${APP_ENV:-dev}
      dockerfile: .docker/mariadb/Dockerfile
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-docker-compose-boilerplate.dev}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - ${MYSQL_PORT:-9033}:3306
    volumes:
      - docker-compose-boilerplate-data:/var/lib/mysql:rw
    networks:
      - docker-compose-boilerplate
###> doctrine/doctrine-bundle ###

  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: docker-compose-boilerplate-pma-${APP_ENV:-dev}
    ports:
      - ${PMA_PORT:-33080}:80
    environment:
      PMA_HOST: ${PMA_HOST:-mariadb}
    depends_on:
      - mariadb
    networks:
      - docker-compose-boilerplate

#  memcached:
#    container_name: docker-compose-boilerplate-memcached-${APP_ENV:-dev}
#    image: memcached:latest
#    networks:
#      - docker-compose-boilerplate
#
#  rabbitmq:
#    container_name: docker-compose-boilerplate-rabbit-${APP_ENV:-dev}
#    image: rabbitmq:3-management-alpine
#    environment:
#      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE:-SWQOKODSQALRPCLNMEQG}
#      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-rabbit}
#      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-rabbit}
#    ports:
#      - ${RABBITMQ_DASHBOARD_PORT:-1919}:15672 # dashboard
#      - ${RABBITMQ_PORT:-5672}:5672
##    volumes:
##      - .docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
#    depends_on:
#      - nginx
#    networks:
#      - docker-compose-boilerplate
#

networks:
  docker-compose-boilerplate:
    driver: bridge

volumes:
###> doctrine/doctrine-bundle ###
  docker-compose-boilerplate-data:
    driver: local
###< doctrine/doctrine-bundle ###