version: '3.5'

services:
###> symfony/mailer ###
  mailer:
    image: mailhog/mailhog
    container_name: docker-compose-boilerplate-mailer-${APP_ENV:-dev}
    ports:
      - ${MAILHOG_PORT:-8025}:8025
###< symfony/mailer ###

###> doctrine/doctrine-bundle ###
  mariadb:
    ports:
      - 9033
###< doctrine/doctrine-bundle ###
